### PR TITLE
use r.RemoteAddr as remote ip when the Query Variable 'addr' is unset

### PR DESCRIPTION
**Pull request by vdweegen**
For improved compatibility with DD-WRT and the underlying itsadyn framework, I've made the following change: When the 'addr' query variable is no provided, the remote address (where the query originates from) is used as the address.

### CODE REVIEW

**Comment by dstapp** [comment]
Hey thank you very much :-) Looks good! I'll test this in the next days and then merge it 👍

**Comment by dstapp** [comment]
@vdweegen Could you please merge my `develop` branch into yours/rebase from it? Just to have basic CI integration. Thanks.

**Comment by vdweegen** [comment]
@dprandzioch Done! I hope this is a useful addition. I have been running in without problems for a couple of days now using DD-WRT v3.0.

**Comment by dstapp** [comment]
Thanks for your contribution and the fast adoption of my changes! I will merge this now but as this has some code duplication from above, I added a remark to refactor this later on. Your change will be released with 1.3.0 as this is currently only on the develop branch. Still, you can use the `:develop` tag on DockerHub to get those changes already now. Build will be done in approx. 1h :)

**Pull request merged**
