### PR TITLE
Allow getting IP address from "X-Real-Ip", "X-Forwarded-For" headers

### PR DESCRIPTION
**Pull request by joshdvir**
Hi, 

I've added some code to allow getting the IP address automatically from "X-Real-Ip", "X-Forwarded-For" headers.

So if the application is behind a Load Balancer there is no need to send the IP address.

Solves #42 and #33

### CODE REVIEW

**Comment by drpdishant** [comment]
This is an Important feature. Considering the scenario where a system uses multiple active interfaces, but only one interface has the externally accessible IP.
This feature will not require user to know which IP is the external one. And the API will automatically update the IP through which the request has been received.

I tested and It works very well.
```
vagrant@ubuntu-bionic:~$ hostname -I
10.0.2.15 192.168.0.11
vagrant@ubuntu-bionic:~$ curl "http://192.168.0.10:8080/update?secret=changeme&domain=node-1"
{"Success":true,"Message":"Updated A record for node-1 to IP address 192.168.0.11","Domain":"node-1","Domains":["node-1"],"Address":"192.168.0.11","AddrType":"A"}
vagrant@ubuntu-bionic:~$ dig +short -t A node-1.example.org @192.168.0.10
192.168.0.11
```

@dprandzioch requesting you to merge it to make it availabe through your repo.

**Comment by dstapp** [comment]
Hey, thanks for adding this. I'll review it shortly and then merge it!

**Comment by dstapp** [comment]
@joshdvir Looks good, but could you please add unit tests for your changes as well? Just to make sure that nothing breaks in the future :-)

I'd do it but I'm  really short in time right now.

**Comment by joshdvir** [comment]
@dprandzioch implemented tests, enjoy.

**Comment by dstapp** [comment]
Perfect, thanks. Also works for me (y).  I'll merge it and publish it to :latest with the next release. Until then, feel free to grab the :develop image :-)

**Pull request merged**
